### PR TITLE
Bugfix/types get y

### PR DESCRIPTION
**Pull request by raedatoui**
bug with retrieving the y value

### CODE REVIEW

**Comment by krux02** [comment]
With bugs like this you can see how much I used this wrapper after initially writing it. But thanks a lot for the pull request.

**Comment by raedatoui** [comment]
no problem! thank you for the wrapper. I am using it heavily right now as I am learning OpenGL from scratch.  there are other go assimp wrappers out there, but they were too convoluted and overkill

**Comment by krux02** [comment]
Even though I don't use this library anymore, becaues you decided to use it, I looked over my implementation and saw something in Quaternion. When you get the quaternion values in an array, they are ordered in (w,x,y,z). That is the order assimp uses internally. In glm (the c++ version) a quaternion is ordered internally (x,y,z,w), even though the constructor expects (w,x,y,z). I casted the quaternions, I did not properly convert them because I assumed that the internal structure would be the same. That was really painpul to learn and did cost me a lot of time.

https://github.com/g-truc/glm/blob/master/glm/gtc/quaternion.hpp#L89
https://github.com/g-truc/glm/blob/master/glm/gtc/quaternion.hpp#L66


I just thought I should mention it, because it feels so related to this bug.

By the way I like that you like this for it's simplicity. I think when a does a lot of stuff, it does something wrong.

**Comment by raedatoui** [comment]
ah, thanks for the tip. I am following tutorials from scratch and when I get to quats, ill let you know if I run into any issues.

**Pull request merged**
